title: "Xiaoxia Xu"
email: "x.xiaoxia@qmul.ac.uk"
institution: "Queen Mary University of London"
position: "Postdoctoral Researcher"
description: "Postdoctoral researcher focusing on 6G antennas & multiple access, AI-driven wireless, and large model over wireless"
google_scholar: "https://scholar.google.com.hk/citations?user=3ifNbp0AAAAJ&hl"

theme_color: "#1F618D"
avatar: "assets/images/avatar.jpg" 

# Build settings
markdown: kramdown
remote_theme: academicpages/academicpages.github.io
title: "Xiaoxia Xu"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Navigation menu (top bar)
nav_pages:
  - name: About
    url: /about/
  - name: Updates
    url: /updates/
  #- name: Publications
    #url: /publications/

# Contact (in footer)
footer:
  show_contact: true
  contact_email: "x.xiaoxia@qmul.ac.uk"

# Appearance
theme_skin: default  # or light/dark/custom
highlight_theme: github

