locale: "en-UK"
title: "Xiaoxia Xu"
title_separator: "-"
name: "Xiaoxia Xu"
email: "x.xiaoxia@qmul.ac.uk"
description: "Postdoctoral researcher focusing on 6G antennas & multiple access, AI-driven wireless, and large model over wireless"
url: "https://xiaoxiaxusummer.github.io"
baseurl: ""
repository: "xiaoxiaxusummer/xiaoxiaxusummer.github.io"

author:
  avatar: "avatar.jpg"
  name: "Xiaoxia Xu"
  bio: "Postdoctoral researcher on 6G advanced antennas & multiple access techniques, AI-native networks, and large model over wireless"
  location: "London, U.K."
  employer: "Queen Mary University of London"
  email: "x.xiaoxia@qmul.ac.uk"
  googlescholar: "https://scholar.google.com.hk/citations?user=3ifNbp0AAAAJ&hl"
  github: "xiaoxiaxusummer"
